---
- name: Deploy application using a docker container
  hosts: "{{ lookup('env','GROUP_OF_HOSTS') }}"
  serial: 1
  gather_facts: false

  tasks:

    - name: Pull image
      docker_image:
        # yamllint disable-line rule:line-length
        name: "{{ lookup('env','REGISTRY_URL') }}/{{ lookup('env','IMAGE_NAME') }}"
        tag: "{{ lookup('env','IMAGE_TAG') }}"
        force: true
      retries: 15
      delay: 3
      register: docker_pull
      until: docker_pull is succeeded
      failed_when: docker_pull is failure

    - name: Deploy application container
      docker_container:
        name: demo
        # yamllint disable-line rule:line-length
        image: "{{ lookup('env','REGISTRY_URL') }}/{{ lookup('env','IMAGE_NAME') }}:{{ lookup('env','IMAGE_TAG') }}"
        state: started
        restart: true
        ports:
          # yamllint disable-line rule:line-length
          - "{{ lookup('env','CONTAINER_PORT') }}:{{ lookup('env','CONTAINER_PORT') }}"
        env:
          PAGE: "{{ lookup('env','PAGE') }}"

    - name: Wait before starting the next deployment
      pause:
        seconds: 10
